### ISSUE TITLE
doesn't compile with Arduino 1.6.3

### ISSUE THREAD

**Issue by roberto-sebastiano** [riotnetwork/MCP4561#1]
Hello,

the mcp4561 library and example don't compile at all with Arduino 1.6.3.
Beside an error with the example, the library fails with this:

/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:42:10: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
   MCP4561::MCP4561(char dev_address) // define the device adress for this instance
          ^
/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:47:10: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
   MCP4561::~MCP4561(){/_nothing to destruct_/};
          ^
/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:49:12: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
 int MCP4561::write(char mem_addr, int setValue) // mem_addr is 00-0F, setvalue is 0-257
            ^
/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:83:21: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
 unsigned int MCP4561::read(char mem_addr)// mem addr 0x00 - 0x0f ( 0-16 )
                     ^
/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:108:12: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
 int MCP4561::openCircuit()// disconnect teh internal connectiuon in the pot, creating an open circuit
            ^
/home/laptop/Arduino/libraries/MCP4561/MCP4561.c:114:12: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
 int MCP4561::enableOutput()// disconnect the internal connectiuon in the pot, creating an open circuit

Can you check ?
Thank you,
Roberto

**Comment by Daniel-dk** [comment]
Ill update it for Arduino 1.6.x in the next few days :)

**Comment by Daniel-dk** [comment]
fixed it, teh file extention was .c, should have been .cpp
